(function(){
  const root = document.getElementById('arena-log');
  if (!root) return;

  // Keep this map independent from Python output so old JSON feeds still render
  // with the correct character identity. Add future agents here, or emit
  // `avatar_style` in feed items and it will take precedence.
  const avatarByAgent = {
    daily_striker: 'pixel_warrior',
    momentum_hunter: 'pixel_warrior',
    weekly_sage: 'pixel_mage',
    theme_raider: 'pixel_mage',
    risk_sentinel: 'pixel_shield',
    discovery_scout: 'pixel_archer',
    contrarian_monk: 'pixel_monk',
    contrarian_quant: 'pixel_monk',
    market_master: 'pixel_master',
    grand_market_analyst: 'pixel_master'
  };

  // Prefer real PNG character art when present. The CSS pixel avatar remains as
  // a fallback so the page never shows broken identity markers if an image file
  // is missing during development.
  const avatarImageByAgent = {
    daily_striker: '/assets/ai-arena/agents/daily_striker.png',
    weekly_sage: '/assets/ai-arena/agents/weekly_sage.png',
    risk_sentinel: '/assets/ai-arena/agents/risk_sentinel.png',
    discovery_scout: '/assets/ai-arena/agents/discovery_scout.png',
    contrarian_monk: '/assets/ai-arena/agents/contrarian_monk.png'
  };

  let feed = [];
  try { feed = JSON.parse(root.dataset.feed || '[]'); } catch(e) { feed = []; }

  // Render visible feed repeatedly.  The site is static: all messages are
  // generated by GitHub Actions, and the browser only reveals already-built
  // lines based on show_at.  No API is called from the browser.
  function visibleFeed(){
    const now = new Date();
    let visible = feed.filter(x => !x.show_at || new Date(x.show_at) <= now);

    // Immediately after a build, many messages may be scheduled in the future.
    // Show a dense opening block so the LAB does not feel empty.
    if (visible.length < 28) visible = feed.slice(0, Math.min(42, feed.length));

    // Keep the log readable.  It is scrollable, but rendering hundreds of rows
    // can be heavy on mobile.
    return visible.slice(-140);
  }

  function render(){
    const visible = visibleFeed();
    root.innerHTML = '';
    for (const item of visible) {
      const row = document.createElement('div');
      row.className = 'chat-line type-' + safeClass(item.type || 'debate');
      const time = item.show_at ? new Date(item.show_at).toLocaleTimeString('en-US', {
        hour:'2-digit', minute:'2-digit', hour12:false, timeZone:'Asia/Tokyo'
      }) + ' JST' : '';
      const avatarStyle = item.avatar_style || avatarByAgent[item.agent_id] || 'pixel_warrior';
      const avatarImage = item.avatar_image || avatarImageByAgent[item.agent_id] || '';
      const avatarHtml = avatarImage
        ? `<div class="chat-icon avatar-shell avatar-chat-shell"><img src="${escapeAttr(avatarImage)}" alt="${escapeAttr(item.agent_name || item.agent_id || 'Agent')}" class="agent-avatar-img chat-avatar-img" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='block';" /><div class="pixel-avatar avatar-small avatar-${safeClass(avatarStyle)} avatar-fallback"><span></span></div></div>`
        : `<div class="chat-icon pixel-avatar avatar-small avatar-${safeClass(avatarStyle)}"><span></span></div>`;
      row.innerHTML = `
        ${avatarHtml}
        <div class="chat-name">${escapeHtml(item.agent_name || item.agent_id || 'Agent')}</div>
        <div class="chat-message">${escapeHtml(item.body || '')}</div>
        <div class="chat-time">${escapeHtml(time)}</div>
        ${item.linked_symbol ? `<div class="chat-symbol">${escapeHtml(item.linked_symbol)}</div>` : ''}
      `;
      root.appendChild(row);
    }
  }

  render();
  // Update once a minute so newly scheduled 5-10 minute messages appear while
  // the page remains open.
  setInterval(render, 60 * 1000);

  function escapeHtml(s){
    return String(s).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  }
  function escapeAttr(s){
    return escapeHtml(s).replace(/`/g, '&#96;');
  }
  function safeClass(s){
    return String(s || '').toLowerCase().replace(/[^a-z0-9_-]/g, '_');
  }
})();
